Veb portal/Models/DefaultSystemValue.cs
namespace Veb_portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class DefaultSystemValue
    {
        public Guid Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [Required]
        [StringLength(100)]
        public string Value { get; set; }
    }
}

Veb portal/Controllers/VPControllers/DefaultSystemValuesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Veb_portal.Models;
using Veb_portal.Models.ModelViews;

namespace Veb_portal.Controllers.VPControllers
{
    [AdminAuthorize(Roles = "Admin")]
    public class DefaultSystemValuesController : Controller
    {
        private VebPortalDb db = new VebPortalDb();

        // GET: DefaultSystemValues
        public ActionResult Index()
        {
            DefaultSystemValuesIndexModel model = new DefaultSystemValuesIndexModel
            {
                DefValues = db.DefaultSystemValues.ToList(),
                Packages = db.Packages.ToList()
            };
            return View(model);
        }

      /*  // GET: DefaultSystemValues/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DefaultSystemValue defaultSystemValue = db.DefaultSystemValues.Find(id);
            if (defaultSystemValue == null)
            {
                return HttpNotFound();
            }
            return View(defaultSystemValue);
        }*/

        // GET: DefaultSystemValues/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DefaultSystemValues/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Value")] DefaultSystemValue defaultSystemValue)
        {
            if (ModelState.IsValid)
            {
                defaultSystemValue.Id = Guid.NewGuid();
                db.DefaultSystemValues.Add(defaultSystemValue);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(defaultSystemValue);
        }

        // GET: DefaultSystemValues/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DefaultSystemValue defaultSystemValue = db.DefaultSystemValues.Find(id);
            if (defaultSystemValue == null)
            {
                return HttpNotFound();
            }
            return View(defaultSystemValue);
        }

        // POST: DefaultSystemValues/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Value")] DefaultSystemValue defaultSystemValue)
        {
            if (ModelState.IsValid)
            {
                db.Entry(defaultSystemValue).State = EntityState.Modified;
                string[] package = { "S", "G", "P"};
                if (package.Contains(defaultSystemValue.Name))
                {

                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(defaultSystemValue);
        }

        // GET: DefaultSystemValues/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DefaultSystemValue defaultSystemValue = db.DefaultSystemValues.Find(id);
            if (defaultSystemValue == null)
            {
                return HttpNotFound();
            }
            return View(defaultSystemValue);
        }

        // POST: DefaultSystemValues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            DefaultSystemValue defaultSystemValue = db.DefaultSystemValues.Find(id);
            db.DefaultSystemValues.Remove(defaultSystemValue);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }


    
}

Veb portal/Controllers/VPControllers/PackagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Veb_portal.Models;

namespace Veb_portal.Controllers.VPControllers
{
    [AdminAuthorize(Roles = "Admin")]
    public class PackagesController : Controller
    {
        private VebPortalDb db = new VebPortalDb();



        // GET: Packages/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Packages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,TokenNumber")] Package package)
        {
            if (ModelState.IsValid)
            {
                package.Id = Guid.NewGuid();
                db.Packages.Add(package);
                db.SaveChanges();
                return RedirectToAction("Index", "DefaultSystemValues");
            }

            return View(package);
        }

        // GET: Packages/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Package package = db.Packages.Find(id);
            if (package == null)
            {
                return HttpNotFound();
            }
            return View(package);
        }

        // POST: Packages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,TokenNumber")] Package package)
        {
            if (ModelState.IsValid)
            {
                db.Entry(package).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "DefaultSystemValues");
            }
            return View(package);
        }
/*
        // GET: Packages/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Package package = db.Packages.Find(id);
            if (package == null)
            {
                return HttpNotFound();
            }
            return View(package);
        }

        // POST: Packages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Package package = db.Packages.Find(id);
            db.Packages.Remove(package);
            db.SaveChanges();
            return RedirectToAction("Index", "DefaultSystemValues");
        }*/

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Veb portal/Views/DefaultSystemValues/Create.cshtml
@model Veb_portal.Models.DefaultSystemValue

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DefaultSystemValue</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", runat = "server" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control", runat = "server" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" runat="server" class="btn btn-form btn-search" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Veb portal/Views/DefaultSystemValues/Delete.cshtml
@model Veb_portal.Models.DefaultSystemValue

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DefaultSystemValue</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <input type="submit" value="Delete" runat="server" class="btn btn-form btn-search" style="margin-left: 181px;"/> 

        </div>
    }
    @Html.ActionLink("Back to List", "Index")
</div>

Veb portal/Views/DefaultSystemValues/Edit.cshtml
@model Veb_portal.Models.DefaultSystemValue

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DefaultSystemValue</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", runat = "server" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control", runat = "server" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" runat="server" class="btn btn-form btn-search" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Veb portal/Views/DefaultSystemValues/Index.cshtml
@model Veb_portal.Models.ModelViews.DefaultSystemValuesIndexModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    #defSysTable {
        width: 100%;
        height: 100%;
    }
</style>


<h2>List of system values:</h2>

<div>
    <p>
        @Html.ActionLink("Create new value", "Create")
    </p>
    <div class="row">
        <div class="col-sm-2">
            @Html.DisplayName("Name")
        </div>
        <div class="col-sm-2">
            @Html.DisplayName("Value")
        </div>
        <div class="col-sm-2"></div>
    </div>
    <div>
        <hr class="col-sm-6" />
    </div>
    <br />
    @foreach (var item in Model.DefValues)
    {
        <div class="row">
            <div class="col-sm-2">
                @Html.DisplayFor(modelItem => item.Name)
            </div>
            <div class="col-sm-2">
                @Html.DisplayFor(modelItem => item.Value)
            </div>
            <div class="col-sm-2">
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </div>
        </div>
    }


    <br />
    <br/>
    <br/>
    <h2>Packages:</h2>
    <p>
        @Html.ActionLink("Create new package", "Create", "Packages")
    </p>
    <div class="row">
        <div class="col-sm-2">
            @Html.DisplayName("Name")
        </div>
        <div class="col-sm-2">
            @Html.DisplayName("Value")
        </div>
        <div class="col-sm-2"></div>
    </div>
    <div>
        <hr class="col-sm-6" />
    </div>
    <br/>
    @foreach (var item in Model.Packages)
    {
        <div class="row">
            <div class="col-sm-2">
                @Html.DisplayFor(modelItem => item.Name)
            </div>
            <div class="col-sm-2">
                @Html.DisplayFor(modelItem => item.TokenNumber)
            </div>
            <div class="col-sm-2">
                @Html.ActionLink("Edit", "Edit", "Packages", new { id = item.Id }, null) 
            </div>
        </div>
    }

</div>